my_crypto_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/db/db_crypto_data.duckdb
      schema: main
      threads: 4
      keepalives_idle: 0
    prod:
      type: duckdb
      path: /opt/airflow/db/db_crypto_data.duckdb
      schema: main
      threads: 4
      keepalives_idle: 0
