version: 2

sources:
  - name: raw_crypto_data
    schema: main
    tables:
      - name: market_chart
        description: "Raw market chart data from CoinGecko API"
        columns:
          - name: prices
            description: "JSON array of [timestamp_ms, price] pairs"
          - name: market_caps  
            description: "JSON array of [timestamp_ms, market_cap] pairs"
          - name: total_volumes
            description: "JSON array of [timestamp_ms, volume] pairs"

models:
  - name: daily_candlestick
    description: "Daily OHLC candlestick data for Bitcoin"
    columns:
      - name: date
        description: "Trading date"
        tests:
          - unique
          - not_null
      - name: opening_price
        description: "Opening price of the day (USD)"
        tests:
          - not_null
      - name: maximum_price
        description: "Highest price of the day (USD)"
        tests:
          - not_null
      - name: minimum_price
        description: "Lowest price of the day (USD)"
        tests:
          - not_null
      - name: closing_price
        description: "Closing price of the day (USD)"
        tests:
          - not_null